### ISSUE TITLE
May be lost a minus in the equation?

### ISSUE THREAD

**Issue by Jiaqi-knight** [dlfivefifty/M3M6LectureNotes#2]
# Lecture 9: Cauchy transforms
1. Cauchy transforms on the interval
    - Plemelj's theorem
2. Hilbert transform
......
are "nice", we can deform  ΓΓ  to be on the contour itself, giving  
$$\phi(z) = **-**{1 \over 2 \pi \I} \int_{-1}^1 {\phi^+(x) - \phi^-(x) \over x - z} \dx$$

**Comment by Jiaqi-knight** [comment]
![捕获](https://user-images.githubusercontent.com/29836538/56501298-d0fc0380-6540-11e9-911b-a21c12fef749.PNG)

**Comment by dlfivefifty** [comment]
I don’t think so: the first equation corresponds to integrating clockwise (without the - sign). This is the same as integrating above the contour left-to-right then below the contour right-to-left.

**Comment by Jiaqi-knight** [comment]
Sorry, It's my fault!!
I was confused with two contours, Thanks.

**Comment by Jiaqi-knight** [comment]
![捕获](https://user-images.githubusercontent.com/29836538/56502556-45d13c80-6545-11e9-90e5-c088967b28a1.PNG)
