### ISSUE TITLE
Can Cauchy transform be applied in Line on complex plane?

### ISSUE THREAD

**Issue by Jiaqi-knight** [dlfivefifty/M3M6LectureNotes#8]
![Screenshot from 2019-05-18 20-39-27](https://user-images.githubusercontent.com/29836538/57969887-14655880-79ad-11e9-9ee9-91e68b709f07.png)
Hello, sir!
Cauchy transform in your package is a magic tool for solving problems, which behind may be fast orthogonal polynomials.
And these days, I also have a problem of Wiener-Hopf method which is the factorization of the kernel function K by Cauchy transform,ref[Nobel 1958] .
**However, the path of integration 𝛾 is from -∞e^{-i𝜖} to +∞e^{i𝜖},with 𝜖->0,which means it is not on real line.
So, my question is could Cauchy transform be applied with curve on complex plane or not? If could, how fast than normal "sum"**

Thank you!
Jiaqi

**Comment by dlfivefifty** [comment]
Yes that's fine. The easiest way is to use a line segment: `Segment(10*exp(-im*ε), 10*exp(im*ε))`, though you could also do `exp(ε*im)Line()`.

**Comment by dlfivefifty** [comment]
Please file an issue if those suggestions don't work.
